spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie
    username: root
    password: black159
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

KMDB:
  key: 4U6V83F44L7Y8VNLF42B

naver:
  url:
    search:
      movie: https://openapi.naver.com/v1/search/local.json

    client:
      id: 13De2BDkkPwBrZddTNyQ
      secret: 5z043okjEz


movie:
  box:
    key: 38b6115a994d498ad200a534627cf969


  servlet:
    multipart:
      enabled: true
      location: D:\\fileupload
      max-file-size: 10MB
      max-request-size: 30MB

file:
  path: D:\\fileupload